spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: config

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVER_USERNAME}:${REGISTRY_SERVER_PASSWORD}@registry:8761/eureka/

server:
  port: 8888

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证 
  user:
    name: ${CONFIG_SERVER_USERNAME}                  # 配置登录的账号是user
    password: ${CONFIG_SERVER_PASSWORD}            # 配置登录的密码是password123
